FROM docker.io/library/tomcat:8.5.15

MAINTAINER "dbswjdahr<yjm011019@naver.com>"

RUN rm -rf /usr/local/tomcat/webapps/

ADD docker/postgresql-9.4.1212.jar /usr/local/tomcat/lib/
ADD target/blog.war /usr/local/tomcat/webapps/ROOT.war
